### PR TITLE
[DO NOT REVIEW][DO NOT MEREG] Add blob type

### PR DESCRIPTION
**Pull request by mattn**
Wait merge https://github.com/vim-jp/vim-vimlparser/pull/92

### CODE REVIEW

**Comment by blueyed** [comment]
Please consider adding a test that would fail now, without https://github.com/vim-jp/vim-vimlparser/pull/92 being merged.

**Comment by mattn** [comment]
okay, will do

**Comment by mattn** [comment]
@blueyed Hi, I looked test code just a little. But I'm not familier to tox testing. Could you please tell me which file I should fix?

**Comment by blueyed** [comment]
@mattn 
Maybe it's better to add a test when using this, e.g. with some new policy for blob types.
Do you have something in mind there maybe already?

**Comment by mattn** [comment]
Currently, I have something problem to use tox on my PC. Sorry. If someone will do, I want to close this.

**Comment by blueyed** [comment]
> Currently, I have something problem to use tox on my PC.

Happy to help there - what is your problem?

> Sorry. If someone will do, I want to close this.

I will update vimlparser soon anyway (#318), so this would only add the type, which then also only makes sense when it is used actually (AFAICS).

**Comment by mattn** [comment]
Sorry, I don't hope that I will be release stopper. If I will have a time to help vint, I make new PR. Thanks.

**Comment by blueyed** [comment]
No worries - this is not blocking any release.. ;)

**Pull request closed without merging**
