### PR TITLE
ProhibitUnnecessaryDoubleQuote should be a style problem, not a warning?

### PR DESCRIPTION
**Pull request by tpope**
Maybe I'm just confused about the various levels, but single versus double quotes seems as stylistic as it gets.

### CODE REVIEW

**Comment by blueyed** [comment]
There is also a bit of overhead with double quotes (due to escape sequences), but have never checked how much that really is.
And then there is also the need to escape things with double quotes, of course.

**Comment by Kuniwak** [comment]
Sorry for my too late reply.

I wrote definitions of severity of Vint to [the wiki](https://github.com/Kuniwak/vint/wiki/Vint-linting-policy-summary#severity-definition). By this definitions, the severity should be warning. Because a newbie who do not understand the difference between single quotes and double quotes can take a mistake when using regexp.
I think it can be style problem if no difference between double quotes and single quotes exists.

**Comment by tpope** [comment]
If it's wontfix, it's wontfix. But this fires on all strings, not regexps, so the main thing it teaches newbies is "don't trust the linter, it's full of false positives".

**Comment by Kuniwak** [comment]
I think a newbie who understand the difference between the single quotes and double quotes, he/she can also understand how to disable the policy. Vint has [the multiple layered configuration](https://github.com/Kuniwak/vint#configure), so you can disable the policy by the one of the layers if you feel the policy is not useful.

**Comment by blueyed** [comment]
The wiki states:

> warning	The detected code does probably not work.

This is not the case really.

`let foo = "bar"` is pretty fine.

> Because a newbie who do not understand the difference between single quotes and double quotes can take a mistake when using regexp.

What would that be?
Not adding an extra backslash only, or something else?

Because then we could make the existing policy a style problem, but add a new one that looks at double quoted strings that contain single escape characters, which are not part of the special escapes (like `\n`).
Does that sound sensible?

**Comment by blueyed** [comment]
Just for postery:



(via https://twitter.com/tpope/status/1007648903842422786)

**Pull request closed without merging**
