### PR TITLE
Neovim support

### PR DESCRIPTION
**Pull request by Kuniwak**
Related #130

### CODE REVIEW

**Comment by RianFuro** [comment]
Dang, you beat me to it :D

**Comment by Kuniwak** [comment]
Oh, I'm sorry!
This achievement would not have been possible without your support.
And I don't know Neovim-specific rules yet, so I always welcome your help.

Thank you very much!

**Comment by Kuniwak** [comment]
This feature shipped with https://github.com/Kuniwak/vint/releases/tag/v0.3.6.
Thank you, @RianFuro ! :rose:

**Comment by jrolfs** [comment]
Looks like this doesn't cover the non-recursive version of `tmap` as I'm seeing errors for the following:

```vim
" Terminal
tnoremap <ESC><ESC> <C-\><C-n>
tnoremap <D-l> clear<CR>

tmap <C-h> <ESC><ESC><C-h>
tmap <C-j> <ESC><ESC><C-j>
tmap <C-k> <ESC><ESC><C-k>
tmap <C-l> <ESC><ESC><C-l>
```

tmap-sad

Should I open a PR to add `tmap` support as well?

**Comment by RianFuro** [comment]
@jrolfs ouch, good catch. No idea how i missed that :/
Basically, we'd need to fix that in vimlparser (https://github.com/ynkdir/vim-vimlparser), but ynkdir seems inactive for almost a year now, so I don't know how much good it'd do us.
@Kuniwak maybe we should opt to resolve it in your local copy instead?

**Comment by jrolfs** [comment]
Seems fairly easy to miss as there's quite a few examples (as well as a plugin or two) around for improving Neovim's default and none of them use `tmap`.

The `<ESC><ESC>` part of my example is a little contrived, however it's really nice to let `<C-l>` etc. expand to the standard pane navigation I have defined (i.e: `<C-l>` → `<C-w><C-l>`).

**Comment by jrolfs** [comment]
@Kuniwak I'll hopefully have time for a PR so let me know what you decide regarding @RianFuro's comment.

**Pull request merged**
