### PR TITLE
Only require mock for tests with Python < 3.3

### PR DESCRIPTION
**Pull request by Coacher**

### CODE REVIEW

**Comment by Kuniwak** [comment]
It seems resolving conflict required.

**Comment by Coacher** [comment]
Indeed. Just a sec.

**Comment by Coacher** [comment]
Fixed.

**Comment by Coacher** [comment]
I'd say this is also not a super important change. Very little gain, but tox.ini receives hardcoding.
It is up to you to decide.

**Comment by Kuniwak** [comment]
Yeah, refactoring is always welcome.
Thanks!

**Comment by Coacher** [comment]
tox upstream considers reusing tests_require from setup.py, see https://bitbucket.org/hpk42/tox/issues/13/tox-should-reuse-tests_require

Hopefully someday it will be fixed as well.

**Pull request merged**
