### PR TITLE
Support :packadd and :packloadall commands

### LINKED ISSUE #210: :packadd and :packloadall should be permitted
Vim 8 added [support for packages](http://vimhelp.appspot.com/repeat.txt.html#packages), with these new commands:

* [`:packadd`](http://vimhelp.appspot.com/repeat.txt.html#%3Apackadd)
* [`:packloadall`](http://vimhelp.appspot.com/repeat.txt.html#%3Apackl)

Currently, vint reports `E492: Not an editor command` if either of these commands appear in a script.

### PR DESCRIPTION
**Pull request by nelstrom**
Fixes #210.

I see that the `vimlparser.py` file that is bundled is meant to be used as a fallback in case the systemwide vimlparser module is not available. Should I be submitting a patch like this to [vim-vimlparser](https://github.com/ynkdir/vim-vimlparser) as well, or instead?

### CODE REVIEW

**Comment by nelstrom** [comment]
It looks like [PR#29](https://github.com/ynkdir/vim-vimlparser/pull/29) includes the `:packadd` and `:packloadall` commands, so I won't submit a PR to that project.

**Comment by Kuniwak** [comment]
Sorry for my late reply.
I'll update vim-vimlparser.

**Comment by Kuniwak** [comment]
I shipped the fixed version as v0.3.13.
Please check it. 

Thanks.

**Comment by nelstrom** [comment]
@Kuniwak I've upgraded to vint `v0.3.13` and it now accepts `:packadd` and `:packloadall` as valid commands. Thanks!

**Pull request closed without merging**
